[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
(
    env
  | env1
  | venv
  | \.venv
  | __pycache__
  | db
  | site-packages
  | \.git
  | \.github
  | build
  | dist
)
'''

[tool.isort]
profile = "black"
line_length = 88


[tool.pytest.ini_options]
pythonpath = "."
addopts = "-v"
